# Generated by Django 4.2.22 on 2025-08-04 23:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('click_through_rate', models.FloatField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_analytics', to='blog.post')),
            ],
        ),
    ]
